id: IDEE984F8
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-16T12:06:48+00:00'
last_modified: '2022-06-10T04:58:57.069151+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W29016
  title: དབུ་མའི་སྤྱི་དོན་སྐལ་བཟང་མགུལ་རྒྱན་གྱི་དགོངས་དོན་གསལ་བར་བྱེད་པའི་ཡང་གསལ་སྒྲོན་མེ།
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
  base:
    F2AA:
      image_group_id: I1PD28110
      title: Volume 1 of dbu ma'i spyi don skal bzang mgul rgyan gyi dgongs don gsal
        bar byed pa'i yang gsal sgron me
      total_pages: 322
      order: 1
      base_file: F2AA.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
